name:                MetaBuilder
version:             0.1.0.0
github:              "MxmUrw/MetaBuilder"
license:             BSD3
author:              "Maxim Urschumzew"
maintainer:          "example@example.com"
copyright:           "2021 Maxim Urschumzew"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MetaBuilder#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - shake
    - filemanip
    - directory
    - text
    - yaml
    - aeson
    - executable-path
    - attoparsec
    - parsec
    - split
    - Agda
  default-extensions:
    - DuplicateRecordFields
    - DeriveGeneric
    - RankNTypes
    - MultiParamTypeClasses
    - FunctionalDependencies

executables:
  metabuild:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MetaBuilder

tests:
  MetaBuilder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MetaBuilder
